# https://github.com/David-Byrne/jekyll-diff-action

name: Jekyll diff
on: [push]

jobs:
  diff-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: David-Byrne/jekyll-diff-action@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
